services:
  # ১. আপনার ফ্লাস্ক অ্যাপ (এখন এটিও কন্টেইনার হবে)
  web_app:
    build: .
    container_name: web_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - prometheus

  # ২. Prometheus (মনিটরিং)
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./src/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # ৩. Grafana (ড্যাশবোর্ড)
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped